# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "u19kwkKsFwPc5SDdQIuoT//DlNP+Kb0wvp+OYNiBLcjwI4UcoecBU+HK3A2uJUrLtUknIZm3oVxPfh1cNpjt5GixJxabr8zA/RqbpBVUBp7zSzzNucHxqE+hAbMlhUKzVbc5QnrA7+6WcYHI7YK88POb/FOa+fmcs9vLM8ikliUP6IIJKbhwmSQpnKiOVel8AQbfHEVUY10KIJBJ1LuqA0cDJ8MutntUcmf5wn1rc4qX4RNYkkai8hrm06HfmbQOsof9EBAFk/dVuehdT7vTXZz9pFynunaVqQ/QCZ+Xl9dSBzm33yz4IUWnNcu1iu50yWnD0LMG3fXMhMRg07anCjT1lXjptHq/N2rMYW5YwbcPJUyQnMlVkw9XyXf155CNTF4LNcjecbC9TJkP10M99A2Yc0SBb5+vAYHEkvFqPY33CB0/MDp7gprW695Rqb7B3uFARMqL2fIlHBLx5ZLUVZZG5H9nbStW1oz7zN7ndMTabldKGAEiO+f3GzYeDSBw0YC8jsXrepA4xoTBikxOJxLjpaleaoSQ4XIxwUzlOanJMKXSnJ/YscpLPNZT57ajIkyr35P3bJX/ZYGlEbnprSWdfLYOfhSrVtiXQdWWiwib/GDpz019tMTBRNsnK0j+4f58JfNIwHuS3YY6BuKdn/3DoV8HRz2jSkJO9e4gfMQ="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi