appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: u19kwkKsFwPc5SDdQIuoT//DlNP+Kb0wvp+OYNiBLcjwI4UcoecBU+HK3A2uJUrLtUknIZm3oVxPfh1cNpjt5GixJxabr8zA/RqbpBVUBp7zSzzNucHxqE+hAbMlhUKzVbc5QnrA7+6WcYHI7YK88POb/FOa+fmcs9vLM8ikliUP6IIJKbhwmSQpnKiOVel8AQbfHEVUY10KIJBJ1LuqA0cDJ8MutntUcmf5wn1rc4qX4RNYkkai8hrm06HfmbQOsof9EBAFk/dVuehdT7vTXZz9pFynunaVqQ/QCZ+Xl9dSBzm33yz4IUWnNcu1iu50yWnD0LMG3fXMhMRg07anCjT1lXjptHq/N2rMYW5YwbcPJUyQnMlVkw9XyXf155CNTF4LNcjecbC9TJkP10M99A2Yc0SBb5+vAYHEkvFqPY33CB0/MDp7gprW695Rqb7B3uFARMqL2fIlHBLx5ZLUVZZG5H9nbStW1oz7zN7ndMTabldKGAEiO+f3GzYeDSBw0YC8jsXrepA4xoTBikxOJxLjpaleaoSQ4XIxwUzlOanJMKXSnJ/YscpLPNZT57ajIkyr35P3bJX/ZYGlEbnprSWdfLYOfhSrVtiXQdWWiwib/GDpz019tMTBRNsnK0j+4f58JfNIwHuS3YY6BuKdn/3DoV8HRz2jSkJO9e4gfMQ=}
bot:
  automerge: true
conda_forge_output_validation: true
